# Generated by Django 3.0.5 on 2020-04-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialish',
            name='facbook_url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='specialish',
            name='linkedin_url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='specialish',
            name='pinterest_url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='specialish',
            name='twitter_url',
            field=models.URLField(default='#'),
        ),
    ]
