# Generated by Django 3.0.5 on 2020-04-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialish', '0003_auto_20200407_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialish',
            name='facbook_url',
            field=models.URLField(blank=True, default='facebook.com', null=True),
        ),
        migrations.AlterField(
            model_name='specialish',
            name='linkedin_url',
            field=models.URLField(blank=True, default='linkedin.com', null=True),
        ),
        migrations.AlterField(
            model_name='specialish',
            name='pinterest_url',
            field=models.URLField(blank=True, default='pinterest.com', null=True),
        ),
        migrations.AlterField(
            model_name='specialish',
            name='twitter_url',
            field=models.URLField(blank=True, default='twitter.com', null=True),
        ),
    ]
